name: deploy

on:
  push:
    branches:
      - main

env:
  AZURE_FUNCTIONAPP_NAME: 'your-app-name'   
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'apps/api'       
  NODE_VERSION: '22.x'     

permissions:
  id-token: write
  contents: read

jobs:
  infra:
    runs-on: ubuntu-latest
    outputs:
      deployed: ${{ steps.deploy.outputs.deployed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check if packages/infra has changes
        id: check
        run: |
          git fetch origin main
          if git diff --quiet origin/main...HEAD -- packages/infra; then
            echo "No infra changes"
            echo "need_deploy=false" >> $GITHUB_OUTPUT
          else
            echo "Infra changes detected"
            echo "need_deploy=true" >> $GITHUB_OUTPUT
          fi

      - name: Azure Login
        if: steps.check.outputs.need_deploy == 'true'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Infrastructure
        if: steps.check.outputs.need_deploy == 'true'
        id: deploy
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: IngestIq
          template: ./packages/infra/main.bicep
          parameters: subscriptionId=${{ secrets.AZURE_SUBSCRIPTION_ID }}

  apps:
    needs: infra
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 9

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm install
          pnpm run turbo build

      - name: Zip api
        run: |
          cd apps/api/dist
          zip -r ../api.zip .

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: .apps/api/api.zip
