name: Stacks (Validate)

on:
  pull_request:
    branches:
      - main

env:
  REGION: 'centralus'
  RESOURCE_GROUP: 'IngestIQ'

permissions:
  contents: read
  id-token: write

jobs:
  validate:
    name: Validate Stack
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Validate
        uses: azure/bicep-deploy@v2
        with:
          type: deploymentStack
          operation: validate
          name: Development
          location: ${{ env.REGION }}
          scope: subscription
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          template-file: ./packages/infra/main.bicep
          action-on-unmanage-resources: delete
          action-on-unmanage-resourcegroups: delete
          deny-settings-mode: none

  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Yarn
        run: corepack enable && corepack prepare yarn@stable --activate

      - name: Install Turbo
        run: npm install -g turbo
        env:
          YARN_CACHE_FOLDER: ${{ github.workspace }}/.yarn-cache

      - name: Install and Build 
        run: |
          yarn install --no-immutable
          turbo build